### ISSUE TITLE
Wie geht es weiter

### ISSUE THREAD

**Issue by miathedev** [HackerspaceBremen/hshb-lightsandmore#1]
Hi @trailblazr, was hast du als nächstes vor?

Ich würde in den nächsten Wochen endlich die LED Strips im Raum installieren und meinen Basis Sketch installieren. Funktionieren tut es ja. 

Wenn du dann irgendwann weiter dran arbeitest kannst du gern deine Änderungen flashen - dann klinke ich mich aber raus wenn das ok ist.

Hast du deine anderen Projekt member kontaktiert?
Wann willst du ein weiteres treffen organisieren? Das ist jetzt knapp 2 Monate her wo du das machen wolltest.

Lg @miathedev

**Comment by trailblazr** [comment]
Hallo @miathedev danke für deine Nachfrage. Ich würde das gerne off-github weiterbesprechen. Derzeit ist meine zur Verfügung stehende zeit sehr begrenzt. Ich schreib dir eine Mail. Wie gesagt möchte ich das nicht hier öffentlich diskutieren, sondern per Mail.
